<a href="https://colab.research.google.com/github/MDTanveerAlam1/Numpy_Assignment/blob/main/Numpy_assignment_module_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# >>> Question number 1
# Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
# >> Answer


# Purpose of NumPy >>

#NumPy is a powerful library in Python used for scientific computing and data analysis.
#It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

# Advantages of NumPy >>

# 1. Efficient Array Operations --> NumPy allows you to perform operations on entire arrays without writing loops, making your code cleaner and faster.

# 2. Speed -->  NumPy is much faster than Python lists because it uses optimized C code behind the scenes.
# 3 Memory Efficiency --> NumPy arrays consume less memory compared to Python lists, which is crucial when working with large datasets.

# 4. Mathematical Functions --> It includes a wide range of mathematical functions, such as linear algebra, statistics, and random number generation.

# 5. Integration --> NumPy integrates well with other libraries like Pandas, Matplotlib, and SciPy, which are essential for data analysis and visualization.

# Enhancing Python's Capabilities >>

# 1 Vectorization --> NumPy allows you to apply operations to entire arrays at once, rather than iterating through elements one by one. This is called vectorization and it significantly speeds up computations.
# 2 Broadcasting --> This feature lets you perform arithmetic operations on arrays of different shapes and sizes without needing to manually reshape them.

In [9]:
# >>> Question Number 2
# Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
# >> Answer

# np.mean() and np.average() are both used to calculate the average of an array, but they differ in how they handle weights.

# np.mean()
# - Calculates the arithmetic mean of an array.
# - It doesn't take any weights into account.
# - It's faster than np.average().

# np.average()
# - Calculates the weighted average of an array.
# - It allows you to specify weights for each element in the array.
# - It's slower than np.mean() because it performs additional computations to handle the weights.

# When to use np.mean()
# - When you want to calculate the simple average of an array without considering any weights.
# - When performance is critical.

# When to use np.average()
# - When you want to calculate the weighted average of an array.
# - When you need more control over how the average is computed, such as specifying custom weights.


# Example
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])

mean = np.mean(arr)
weighted_average = np.average(arr, weights=weights)

print("Mean:", mean)
print("Weighted Average:", weighted_average)


Mean: 3.0
Weighted Average: 3.2


In [10]:
# >>> Question Number 3
# Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays
# >> Answer

import numpy as np

# Reversing a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = np.flip(arr_1d)
print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_arr_1d)

# Reversing a 2D array along different axes
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr_2d_axis0 = np.flip(arr_2d, axis=0)  # Reverses rows
reversed_arr_2d_axis1 = np.flip(arr_2d, axis=1)  # Reverses columns

print("\nOriginal 2D array:\n", arr_2d)
print("\nReversed 2D array along axis 0:\n", reversed_arr_2d_axis0)
print("\nReversed 2D array along axis 1:\n", reversed_arr_2d_axis1)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Reversed 2D array along axis 0:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]

Reversed 2D array along axis 1:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [11]:
# >>> Question Number 4
#  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance
# >> Answer

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
data_type = arr.dtype
print("Data type of the array:", data_type)

# Importance of Data Types in Memory Management and Performance -->>

# 1. Memory Management >
#    - Different data types occupy different amounts of memory. For example, an integer (int) takes up less memory than a floating-point number (float).
#    - By choosing the appropriate data type for your array, you can optimize memory usage, especially when working with large datasets.

# 2. Performance >>
#    - The data type also influences the performance of operations on the array.
#    - NumPy is optimized to perform operations on arrays with homogeneous data types efficiently.
#    - When using the correct data type, you can achieve better performance for numerical calculations.


# Example >>
# If you have an array that only contains integers, but you use a floating-point data type,
# it will consume more memory than necessary, and computations might be slower
# than if you had used an integer data type.

Data type of the array: int64


In [12]:
# >>> Question Number 5
# Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
# >> Answer

# ndarrays in NumPy (N-dimensional arrays)

# Definition -->>>
# - ndarrays are multi-dimensional arrays that form the core of NumPy.
# - They are homogeneous, meaning they contain elements of the same data type.
# - They are mutable, which means you can change their contents after creation.


# Key Features -->

# 1. Homogeneity: All elements within an ndarray must have the same data type. This allows NumPy to optimize memory usage and calculations.
# 2. Shape and Dimensionality: ndarrays have a shape that defines their dimensions (e.g., a 2x3 array has 2 rows and 3 columns).
# 3. Data Type: Each ndarray has a data type that specifies the type of elements it holds (e.g., int, float, complex).
# 4. Vectorized Operations: NumPy provides functions that allow you to perform operations on entire arrays without writing loops, making your code faster and easier to read.
# 5. Broadcasting: NumPy allows you to perform operations on arrays of different shapes and sizes, making it easier to manipulate data.


# Differences from Standard Python Lists -->>

# 1. Homogeneity vs. Heterogeneity>>
#   - ndarrays are homogeneous (same data type) while Python lists can hold elements of different data types.
# 2. Performance >>
#   - ndarrays are significantly faster for numerical operations due to their optimized internal structure and vectorized operations.
# 3. Functionality >
#   - NumPy provides a wider range of mathematical functions and tools for working with arrays than standard Python lists.
# 4. Memory Usage >>
#   - NumPy arrays are generally more memory-efficient than Python lists because they store data in a contiguous block of memory.
# 5. Vectorization and Broadcasting >>
#   - These features, only available in ndarrays, allow you to perform element-wise operations and manipulate arrays of different shapes efficiently.


# Code >>
import numpy as np
list_data = [1, 2.5, 'hello'] # Python list (heterogeneous)

array_data = np.array([1, 2, 3, 4, 5]) # NumPy ndarray (homogeneous)

In [13]:
# >>> Question Number 6
#  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
# >> Answer

# NumPy arrays are faster than Python lists for large-scale numerical operations because:

# 1. Vectorized Operations >>  NumPy allows you to perform operations on entire arrays at once, rather than iterating through elements one by one.
# This is called vectorization and it significantly speeds up computations.

# 2. Optimized Code >>  NumPy is written in C and uses optimized algorithms, which makes it much faster than Python lists for numerical operations.

# 3. Memory Efficiency >>  NumPy arrays are more memory-efficient than Python lists because they store data in a contiguous block of memory.

# 4. Specialized Functions >>  NumPy provides a wide range of specialized functions for numerical operations, such as linear algebra, statistics, and random number generation.
# These functions are highly optimized and can perform calculations much faster than Python code.


In [14]:
# >>> Question Number 7
# Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output
# >> Answer

import numpy as np

# vstack() (Vertical Stacking)
# - Combines arrays vertically, stacking them on top of each other.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

vertical_stack = np.vstack((arr1, arr2))
print("vstack Result:\n", vertical_stack)



# hstack() (Horizontal Stacking)
# - Combines arrays horizontally, placing them side by side.

arr3 = np.array([1, 2, 3])
arr4 = np.array([4, 5, 6])

horizontal_stack = np.hstack((arr3, arr4))
print("\nhstack Result:\n", horizontal_stack)

vstack Result:
 [[1 2 3]
 [4 5 6]]

hstack Result:
 [1 2 3 4 5 6]


In [15]:
# >>> Question Number 8
#  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions
# >> Answer

import numpy as np

# Let's imagine you have a photo represented by a 2D array (like a grid of pixel colors).

# fliplr() (Flip Left-Right)
# It flips the array horizontally, like mirroring the photo from left to right.
# in simple words we can say that the fliplr() makes a mirror image of your array from left to right.

photo = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

flipped_left_right = np.fliplr(photo)

print("Original Photo:")
print(photo)
print("\nFlipped Left-Right:")
print(flipped_left_right)

# flipud() (Flip Up-Down)
# It flips the array vertically, like turning the photo upside down.
# in simple words we can say that flipud() makes a mirror image of your array from top to bottom.

photo = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

flipped_up_down = np.flipud(photo)

print("\nOriginal Photo:")
print(photo)
print("\nFlipped Up-Down:")
print(flipped_up_down)

Original Photo:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Left-Right:
[[3 2 1]
 [6 5 4]
 [9 8 7]]

Original Photo:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Up-Down:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [16]:
# >>> Question Number 9
#  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
# >> Answer

import numpy as np

# Example array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array into 3 equal parts (if possible)
split_arr = np.array_split(arr, 3)
print("Split array:", split_arr)

# Explanation -- >>
# - array_split() is used to divide a NumPy array into multiple sub-arrays.
# - It takes two arguments >> the array to be split and the number of splits you want.

# Uneven Splits -- >>
# - If the array cannot be divided evenly into the desired number of parts,
#   array_split() will create sub-arrays with varying lengths.
# - The last sub-array might have a different size to ensure all elements are included.


# Example >>
arr2 = np.array([1, 2, 3, 4, 5, 6, 7])
split_arr2 = np.array_split(arr2, 3)
print("Uneven split:", split_arr2)

Split array: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
Uneven split: [array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [17]:
# >>> Question Number 10
#  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
# >> Answer


# Vectorization and Broadcasting in NumPy >>

# Vectorization >>
# - Vectorization is the process of applying operations to entire arrays at once, without using explicit loops.
# - This eliminates the need to iterate through individual elements, resulting in significantly faster and more efficient code.

# Broadcasting >>
# - Broadcasting is a set of rules that allow NumPy to perform operations on arrays of different shapes and sizes.
# - It automatically adjusts the shapes of arrays to make them compatible for element-wise operations.

# How they Contribute to Efficient Array Operations >>

# 1. Speed and Performance -->
#    - Both vectorization and broadcasting are implemented using optimized C code, making them much faster than Python loops.
#    - This leads to significant performance gains, especially when working with large arrays.

# 2. Readability and Conciseness -->
#    - Vectorized operations and broadcasting enable you to write more concise and readable code.
#    - You can express complex array manipulations in fewer lines, making your code easier to understand and maintain.

# 3. Efficient Memory Usage -->
#    - Vectorization and broadcasting can help reduce memory consumption by avoiding unnecessary array copies.
#    - They allow you to manipulate data directly in memory, leading to more efficient resource utilization.


# Example >>

# Vectorization:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition using vectorization
result = arr1 + arr2

print("Vectorized addition:", result)

# Broadcasting:

arr3 = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

# Multiplying an array by a scalar using broadcasting
result_broadcasting = arr3 * scalar

print("Broadcasting:", result_broadcasting)

# In the vectorization example, NumPy applies the addition operation to the entire arrays without needing explicit loops.
# In the broadcasting example, NumPy automatically expands the scalar value '2' to match the shape of 'arr3', allowing element-wise multiplication.

Vectorized addition: [5 7 9]
Broadcasting: [[ 2  4  6]
 [ 8 10 12]]
