<a href="https://colab.research.google.com/github/MDTanveerAlam1/Numpy_Assignment/blob/main/Practical_Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practical Solution Numpy assignment

In [15]:
# Question Number 1
# Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
#  >>>   Answer   <<<

import numpy as np

# --> 3x3 NumPy array with random integers between 1 and 100 >>
array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns using array transpose >>>
interchanged_array = array.transpose()

print("Original Array:")
print(array)
print("Interchanged Array:")
print(interchanged_array)

Original Array:
[[54 63 12]
 [64 41 98]
 [26 95 32]]
Interchanged Array:
[[54 64 26]
 [63 41 95]
 [12 98 32]]


In [17]:
# Question Number 2
#  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
#  >>>   Answer   <<<

import numpy as np
# 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("Original 1D Array:")
print(array_1d)
print("Reshaped 2x5 Array:")
print(array_2x5)
print("Reshaped 5x2 Array:")
print(array_5x2)

Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]
Reshaped 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
# Question Number 3
# Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
#  >>>   Answer   <<<

import numpy as np
# Create a 4x4 NumPy array with random float values >>
array_4x4 = np.random.rand(4, 4)

# Create a 6x6 array filled with zeros >>>
array_6x6 = np.zeros((6, 6))

# Insert the 4x4 array into the center of the 6x6 array >>>
array_6x6[1:5, 1:5] = array_4x4

print("Original 4x4 Array:")
print(array_4x4)
print("6x6 Array with Zero Border:")
print(array_6x6)

Original 4x4 Array:
[[0.24001313 0.74733973 0.71708214 0.66081822]
 [0.14937322 0.62571483 0.32794743 0.99689718]
 [0.92119146 0.92393434 0.40237873 0.00428615]
 [0.98861807 0.28630327 0.62884968 0.9182215 ]]
6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.24001313 0.74733973 0.71708214 0.66081822 0.        ]
 [0.         0.14937322 0.62571483 0.32794743 0.99689718 0.        ]
 [0.         0.92119146 0.92393434 0.40237873 0.00428615 0.        ]
 [0.         0.98861807 0.28630327 0.62884968 0.9182215  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [21]:
# Question Number 4
# Using NumPy, create an array of integers from 10 to 60 with a step of 5.
#  >>>   Answer   <<<

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print(array)

[10 15 20 25 30 35 40 45 50 55 60]


In [23]:
# Question Number 5
# Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
#  >>>   Answer   <<<

import numpy as np

# >>>  Create a NumPy array of strings
strings_array = np.array(['python', 'numpy', 'pandas'])

# >>>  Apply different case transformations
uppercase_array = np.char.upper(strings_array)
lowercase_array = np.char.lower(strings_array)
titlecase_array = np.char.title(strings_array)

print("Original Array:", strings_array)
print("Uppercase Array:", uppercase_array)
print("Lowercase Array:", lowercase_array)
print("Titlecase Array:", titlecase_array)

Original Array: ['python' 'numpy' 'pandas']
Uppercase Array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase Array: ['python' 'numpy' 'pandas']
Titlecase Array: ['Python' 'Numpy' 'Pandas']


In [26]:
# Question Number 6
# Generate a NumPy array of words. Insert a space between each character of every word in the array
#  >>>   Answer   <<<

import numpy as np

# Generate a NumPy array of words
words_array = np.array(['MD', 'Tanveer', 'Alam'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

print(spaced_words_array)

['M D' 'T a n v e e r' 'A l a m']


In [28]:
# Question Number 7
# Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
#  >>>   Answer   <<<

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# >>Element-wise addition
addition_result = array1 + array2
print("Element-wise Addition:")
print(addition_result)

# >> Element-wise subtraction
subtraction_result = array1 - array2
print("Element-wise Subtraction:")
print(subtraction_result)

# >>Element-wise multiplication
multiplication_result = array1 * array2
print("Element-wise Multiplication:")
print(multiplication_result)

# >>Element-wise division
division_result = array1 / array2
print("Element-wise Division:")
print(division_result)

Element-wise Addition:
[[ 6  8]
 [10 12]]
Element-wise Subtraction:
[[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
[[ 5 12]
 [21 32]]
Element-wise Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [29]:
# Question Number 8
# Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
#  >>>   Answer   <<<

# Create a 5x5 identity matrix -->>
identity_matrix = np.identity(5)

# Extract the diagonal elements -->>
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)
print("Diagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
[1. 1. 1. 1. 1.]


In [30]:
# Question Number 9
# Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array
#  >>>   Answer   <<<

import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, 100)

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

print("Random Array of 100 Integers:")
print(random_array)
print("Prime Numbers in the Array:")
print(prime_numbers)

# this question >> i solved in approx 45 min

Random Array of 100 Integers:
[ 606  715  768  904  188  996  275  737  566  111  661  137  817  120
   75  342  825  768  842  666  311  951  313   82  695  924   15  612
  506  784  573  322  418  167  256  424   94  574  197  769  535  685
  776  750  317  219  459  173   92   35  908  154  896  601  988  674
  872  925   44  875  246  243  757  752   29   27  176  503  952  236
  518  723  994  293  236  435  435  219    1  300  801  417  505  573
  681  758  427  544  498  657  990  632  598  105  559  229  149 1000
  663  397]
Prime Numbers in the Array:
[661, 137, 311, 313, 167, 197, 769, 317, 173, 601, 757, 29, 503, 293, 229, 149, 397]


In [33]:
# Question Number 10
#. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages
#  >>>   Answer   <<<

import numpy as np

# a NumPy array representing daily temperatures for a month
daily_temperatures = np.random.randint(15, 35, 30)

# Calculate weekly averages using list comprehension
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, 30, 7)]

print("Daily Temperatures:")
print(daily_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures:
[29 16 26 15 29 20 15 24 33 34 25 16 16 30 21 29 29 27 22 24 20 32 32 22
 23 17 23 28 16 23]

Weekly Averages:
[21.428571428571427, 25.428571428571427, 24.571428571428573, 25.285714285714285, 19.5]
